import { defineObject, FieldType } from 'twenty-sdk/define';
import { IDS } from '../constants/universal-identifiers';

export default defineObject({
  universalIdentifier: IDS.INTAKE_SOURCE_OBJECT,
  nameSingular: 'intakeSource',
  namePlural: 'intakeSources',
  labelSingular: 'Intake Source',
  labelPlural: 'Intake Sources',
  description: 'A registered webhook source that sends leads into Intake.',
  icon: 'IconRadar2',
  fields: [
    {
      universalIdentifier: IDS.INTAKE_SOURCE_NAME,
      name: 'name',
      type: FieldType.TEXT,
      label: 'Name',
      description: 'Human-readable name for this source.',
      icon: 'IconTag',
    },
    {
      universalIdentifier: IDS.INTAKE_SOURCE_SLUG,
      name: 'slug',
      type: FieldType.TEXT,
      label: 'Slug',
      description: 'URL segment — must be unique. e.g. "contact-form"',
      icon: 'IconLink',
    },
    {
      universalIdentifier: IDS.INTAKE_SOURCE_TARGET_OBJECT,
      name: 'targetObject',
      type: FieldType.SELECT,
      label: 'Target Object',
      description: 'Whether payloads create a Person, Company, or auto-detect.',
      icon: 'IconTarget',
      options: [
        { value: 'AUTO', label: 'Auto-detect', position: 0, color: 'gray' },
        { value: 'PERSON', label: 'Person', position: 1, color: 'blue' },
        { value: 'COMPANY', label: 'Company', position: 2, color: 'green' },
      ],
      defaultValue: "'AUTO'",
    },
    {
      universalIdentifier: IDS.INTAKE_SOURCE_SECRET,
      name: 'webhookSecret',
      type: FieldType.TEXT,
      label: 'Webhook Secret',
      description: 'HMAC-SHA256 signing secret. Leave empty to skip signature verification.',
      icon: 'IconLock',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: IDS.INTAKE_SOURCE_STATUS,
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      icon: 'IconCircleDot',
      options: [
        { value: 'ACTIVE', label: 'Active', position: 0, color: 'green' },
        { value: 'PAUSED', label: 'Paused', position: 1, color: 'yellow' },
      ],
      defaultValue: "'ACTIVE'",
    },
    {
      universalIdentifier: IDS.INTAKE_SOURCE_CREATE_OPP,
      name: 'createOpportunity',
      type: FieldType.BOOLEAN,
      label: 'Auto-create Opportunity',
      description: 'Automatically create an Opportunity linked to each new record.',
      icon: 'IconTrendingUp',
      defaultValue: "'true'",
    },
    {
      universalIdentifier: IDS.INTAKE_SOURCE_OPP_TEMPLATE,
      name: 'opportunityNameTemplate',
      type: FieldType.TEXT,
      label: 'Opportunity Name Template',
      description: 'Template for opportunity names. Use {{source}}, {{firstName}}, {{lastName}}, {{company}}, {{email}}.',
      icon: 'IconTemplate',
      defaultValue: "'{{source}} — {{firstName}} {{lastName}}'",
    },
    {
      universalIdentifier: IDS.INTAKE_SOURCE_TOTAL_INGESTED,
      name: 'totalIngested',
      type: FieldType.NUMBER,
      label: 'Total Ingested',
      icon: 'IconArrowDown',
      defaultValue: 0,
    },
    {
      universalIdentifier: IDS.INTAKE_SOURCE_TOTAL_FAILED,
      name: 'totalFailed',
      type: FieldType.NUMBER,
      label: 'Total Failed',
      icon: 'IconAlertTriangle',
      defaultValue: 0,
    },
    {
      universalIdentifier: IDS.INTAKE_SOURCE_LAST_INGESTED,
      name: 'lastIngestedAt',
      type: FieldType.DATE_TIME,
      label: 'Last Ingested At',
      icon: 'IconClock',
      isNullable: true,
      defaultValue: null,
    },
  ],
});
