import { defineObject, FieldType, RelationType, OnDeleteAction } from 'twenty-sdk/define';
import { IDS } from '../constants/universal-identifiers';

export default defineObject({
  universalIdentifier: IDS.INTAKE_LOG_OBJECT,
  nameSingular: 'intakeLog',
  namePlural: 'intakeLogs',
  labelSingular: 'Intake Log',
  labelPlural: 'Intake Logs',
  description: 'Full audit trail of every payload received by Intake.',
  icon: 'IconListDetails',
  fields: [
    {
      universalIdentifier: IDS.INTAKE_LOG_STATUS,
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      icon: 'IconCircleDot',
      options: [
        { value: 'SUCCESS', label: 'Success', position: 0, color: 'green' },
        { value: 'PARTIAL', label: 'Partial', position: 1, color: 'yellow' },
        { value: 'FAILED', label: 'Failed', position: 2, color: 'red' },
        { value: 'DUPLICATE', label: 'Duplicate', position: 3, color: 'gray' },
      ],
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_PAYLOAD_HASH,
      name: 'payloadHash',
      type: FieldType.TEXT,
      label: 'Payload Hash',
      description: 'SHA-256 hash of the raw payload, used for idempotency.',
      icon: 'IconFingerprint',
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_RECORD_ID,
      name: 'recordId',
      type: FieldType.TEXT,
      label: 'Record ID',
      description: 'ID of the created or updated CRM record.',
      icon: 'IconId',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_RECORD_TYPE,
      name: 'recordType',
      type: FieldType.SELECT,
      label: 'Record Type',
      icon: 'IconDatabase',
      options: [
        { value: 'PERSON', label: 'Person', position: 0, color: 'blue' },
        { value: 'COMPANY', label: 'Company', position: 1, color: 'green' },
      ],
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_FIELDS_CREATED,
      name: 'fieldsCreated',
      type: FieldType.NUMBER,
      label: 'Fields Created',
      description: 'New schema fields added during this ingestion.',
      icon: 'IconPlus',
      defaultValue: 0,
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_FIELDS_MATCHED,
      name: 'fieldsMatched',
      type: FieldType.NUMBER,
      label: 'Fields Matched',
      description: 'Existing fields successfully populated.',
      icon: 'IconCheck',
      defaultValue: 0,
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_OVERFLOW_COUNT,
      name: 'overflowCount',
      type: FieldType.NUMBER,
      label: 'Overflow Fields',
      description: 'Fields that could not be normalised and went into the note.',
      icon: 'IconNotes',
      defaultValue: 0,
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_PROCESSING_MS,
      name: 'processingMs',
      type: FieldType.NUMBER,
      label: 'Processing Time (ms)',
      icon: 'IconClock',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_ERROR,
      name: 'error',
      type: FieldType.TEXT,
      label: 'Error',
      icon: 'IconAlertCircle',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_PROCESSED_AT,
      name: 'processedAt',
      type: FieldType.DATE_TIME,
      label: 'Processed At',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_RAW_PAYLOAD,
      name: 'rawPayload',
      type: FieldType.TEXT,
      label: 'Raw Payload',
      description: 'The original JSON payload — used for retrying failed ingestions.',
      icon: 'IconCode',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: IDS.INTAKE_LOG_SOURCE_RELATION,
      name: 'intakeSource',
      type: FieldType.RELATION,
      label: 'Source',
      icon: 'IconRadar2',
      isNullable: true,
      defaultValue: null,
      relationTargetObjectMetadataUniversalIdentifier: IDS.INTAKE_SOURCE_OBJECT,
      relationTargetFieldMetadataUniversalIdentifier: IDS.INTAKE_SOURCE_LOGS_REVERSE,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'intakeSourceId',
      },
    },
  ],
});
